# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lectern < Formula
  desc "Keyboard-driven TUI for navigating OpenSpec project artifacts"
  homepage "https://github.com/danshort/lectern"
  version "0.21.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danshort/lectern/releases/download/v0.21.0/lectern-darwin-amd64.tar.gz"
      sha256 "7e28761714c26a65f9087716905d2cb1134c43ae25e14ccb1b5d4456cb6ac9ff"

      define_method(:install) do
        bin.install "lectern"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danshort/lectern/releases/download/v0.21.0/lectern-darwin-arm64.tar.gz"
      sha256 "539293b27727a0641785b42cb70bab465bb57a2abe5e5d6abaab0848be5517e4"

      define_method(:install) do
        bin.install "lectern"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danshort/lectern/releases/download/v0.21.0/lectern-linux-amd64.tar.gz"
      sha256 "b96a4ef6dac30ba6d7e74d3d8dacc0248cba8c14f32d74f1f5e2635c2d9cccad"
      define_method(:install) do
        bin.install "lectern"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danshort/lectern/releases/download/v0.21.0/lectern-linux-arm64.tar.gz"
      sha256 "90af933221d70ad76d47587644fe9825f9db25594a2ab9940b7d54f17617834c"
      define_method(:install) do
        bin.install "lectern"
      end
    end
  end

  test do
    system "#{bin}/lectern", "--version"
  end
end
