# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lectern < Formula
  desc "Keyboard-driven TUI for navigating OpenSpec project artifacts"
  homepage "https://github.com/danshort/lectern"
  version "0.17.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danshort/lectern/releases/download/v0.17.0/lectern-darwin-amd64.tar.gz"
      sha256 "b66e761408ffa26ea0399d38ed659ef06ef94b566f313afc40621dbbbab413f5"

      define_method(:install) do
        bin.install "lectern"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danshort/lectern/releases/download/v0.17.0/lectern-darwin-arm64.tar.gz"
      sha256 "2e62e91d0d14a4a98d11ead6b1fa0b031db8c902d9978d7058ee9b906fd6dccb"

      define_method(:install) do
        bin.install "lectern"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danshort/lectern/releases/download/v0.17.0/lectern-linux-amd64.tar.gz"
      sha256 "a2af6bfa04c1db8a877fbaae1f704554bb6c1eda4111d48a09d5d252bae3bf7c"
      define_method(:install) do
        bin.install "lectern"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danshort/lectern/releases/download/v0.17.0/lectern-linux-arm64.tar.gz"
      sha256 "bb3d4b2af2f1b0836011ad8780dee34856d85e19a26714ec944fadee346ca319"
      define_method(:install) do
        bin.install "lectern"
      end
    end
  end

  test do
    system "#{bin}/lectern", "--version"
  end
end
