# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Speclio < Formula
  desc "Keyboard-driven TUI for navigating OpenSpec project artifacts"
  homepage "https://github.com/danshort/speclio"
  version "0.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danshort/speclio/releases/download/v0.15.0/speclio-darwin-amd64.tar.gz"
      sha256 "6db2c004303db1eb380f0f66e44f2b3a7b65098b56f851ab87a748223141d4ab"

      define_method(:install) do
        bin.install "speclio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danshort/speclio/releases/download/v0.15.0/speclio-darwin-arm64.tar.gz"
      sha256 "6341d4f333ca037c9afe992d87d9f45d8cb6e683ebf0f82942a3c0a0b4b34639"

      define_method(:install) do
        bin.install "speclio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danshort/speclio/releases/download/v0.15.0/speclio-linux-amd64.tar.gz"
      sha256 "2a9defca885c20faa76d6764a747c09e7406532c04103e51aa32e88068eebf28"
      define_method(:install) do
        bin.install "speclio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danshort/speclio/releases/download/v0.15.0/speclio-linux-arm64.tar.gz"
      sha256 "505794b1004afc7cf10edfd79c34ff2a7d8a451c9b920e8e1c3526e8182783f0"
      define_method(:install) do
        bin.install "speclio"
      end
    end
  end

  test do
    system "#{bin}/speclio", "--version"
  end
end
